spring:

  application:
    name:
      guitar-tracker

  datasource:
    url: ${DATABASE_URL}
    username: ${DATABASE_USERNAME}
    password: ${DATABASE_PASSWORD}

  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true

server:
  port: 8181

app:
  jwt:
    secret-key: ${JWT_SECRET_KEY}
    access-token-expiration: 60000 # 1 minute in milliseconds
    refresh-token-expiration: 604800000 # 7 days in milliseconds
